name: Build Kernel DTB Only

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y bc bison flex libssl-dev make \
        libc6-dev libncurses5-dev clang lld llvm

    - name: Setup Clang
      run: |
        git clone --depth=1 https://github.com/llvm/llvm-project clang

    - name: Export Build Vars
      run: |
        echo "ARCH=arm64" >> $GITHUB_ENV
        echo "SUBARCH=arm64" >> $GITHUB_ENV
        echo "CLANG_PATH=$GITHUB_WORKSPACE/clang" >> $GITHUB_ENV

    - name: Load Defconfig
      run: |
        make O=out ARCH=arm64 dandelion_defconfig

    - name: Build Image.gz-dtb
      run: |
        make -j$(nproc) O=out \
        ARCH=arm64 \
        CC=clang \
        LD=ld.lld \
        AR=llvm-ar \
        NM=llvm-nm \
        OBJCOPY=llvm-objcopy \
        OBJDUMP=llvm-objdump \
        STRIP=llvm-strip \
        CROSS_COMPILE=aarch64-linux-gnu- \
        CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
        Image.gz-dtb

    - name: Upload DTB Image
      uses: actions/upload-artifact@v4
      with:
        name: kernel_dtb
        path: out/arch/arm64/boot/Image.gz-dtb
