name: Build Kernel DTB (Dandelion)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y bc bison flex libssl-dev make \
        libc6-dev libncurses5-dev python3 cpio unzip zip

    - name: Clone Proton Clang
      run: |
        git clone --depth=1 https://github.com/kdrag0n/proton-clang clang

    - name: Set Environment
      run: |
        echo "ARCH=arm64" >> $GITHUB_ENV
        echo "SUBARCH=arm64" >> $GITHUB_ENV
        echo "PATH=$GITHUB_WORKSPACE/clang/bin:$PATH" >> $GITHUB_ENV

    - name: Create Output Folder
      run: mkdir -p out

    - name: Load Defconfig
      run: |
        make O=out ARCH=arm64 dandelion_defconfig

    # 🔥 Fix lỗi compiler (stack protector)
    - name: Fix Stack Protector Error
      run: |
        scripts/config --file out/.config -d CC_STACKPROTECTOR_STRONG
        scripts/config --file out/.config -e CC_STACKPROTECTOR_NONE
        make O=out ARCH=arm64 olddefconfig

    - name: Build Image.gz-dtb
      run: |
        make -j$(nproc) O=out \
        ARCH=arm64 \
        CC=clang \
        CLANG_TRIPLE=aarch64-linux-gnu- \
        CROSS_COMPILE=aarch64-linux-gnu- \
        CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
        Image.gz-dtb

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: kernel_dtb
        path: out/arch/arm64/boot/Image.gz-dtb
